<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fBVDxrY' shared service.

return $this->privates['.service_locator.fBVDxrY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\OwnerController::show' => ['privates', '.service_locator.1sVfNg4', 'get_ServiceLocator_1sVfNg4Service.php', true],
    'App\\Controller\\RegionController::show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4tv7bhr', 'get_ServiceLocator_4tv7bhrService.php', true],
    'App\\Controller\\RoomController::show' => ['privates', '.service_locator.BkOHXLl', 'get_ServiceLocator_BkOHXLlService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\OwnerController:show' => ['privates', '.service_locator.1sVfNg4', 'get_ServiceLocator_1sVfNg4Service.php', true],
    'App\\Controller\\RegionController:show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4tv7bhr', 'get_ServiceLocator_4tv7bhrService.php', true],
    'App\\Controller\\RoomController:show' => ['privates', '.service_locator.BkOHXLl', 'get_ServiceLocator_BkOHXLlService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\OwnerController::show' => '?',
    'App\\Controller\\RegionController::show' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\RoomController::show' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\OwnerController:show' => '?',
    'App\\Controller\\RegionController:show' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\RoomController:show' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
