<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAJCqcC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAJCqcC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAJCqcC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAJCqcC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOAJCqcC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OAJCqcC',
    'container.build_id' => '8083a81f',
    'container.build_time' => 1573551828,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAJCqcC');
