<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0yU3Hhv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0yU3Hhv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0yU3Hhv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0yU3Hhv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0yU3Hhv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0yU3Hhv',
    'container.build_id' => '698d86a7',
    'container.build_time' => 1573565861,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0yU3Hhv');
